<a href="https://colab.research.google.com/github/pngy87/-PTDLNC-GOOGLE-COLAB/blob/main/%5BCHAPTER%201%5D1_Python_review.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#A. Python Data structure

https://docs.python.org/3/tutorial/datastructures.html

https://thomas-cokelaer.info/tutorials/python/data_structures.html

**1: List,set, tuple; 2: strings, 3:Dicts** **bold text**


**1: List,set, tuple**

**1.1: List**

In [ ]:
#create new list
list_1 = [123,"text1","text2"]

In [ ]:
# display all element of a list.
list_1

[123, 'text1', 'text2']

In [ ]:
#another way to display by using print() function
print(list_1)

[123, 'text1', 'text2']


In [ ]:
#Display the first element of the list
list_1[0]

123

In [ ]:
#update the first element of the list
list_1[0]= "text0" # write to list

In [ ]:
# Adding elements
list_1.append("orange")
print("After adding an element:", list_1)

After adding an element: ['text0', 'text1', 'text2', 'orange']


In [ ]:
# Removing elements
list_1.remove("text2")  # Removes the first occurrence of "apple"
print("After removing an element:", list_1)

After removing an element: ['text0', 'text1', 'orange']


1.2 **Set**

In [ ]:
# 3. Sets: Unordered, Mutable, Do Not Allow Duplicates
# Creating a set
unique_numbers = {1, 2, 3, 4, 4, 5}
print("Original set (duplicates removed):", unique_numbers)

Original set (duplicates removed): {1, 2, 3, 4, 5}


In [ ]:
# Adding elements
unique_numbers.add(6)
print("After adding an element:", unique_numbers)

After adding an element: {1, 2, 3, 4, 5, 6}


In [ ]:
# Removing elements
unique_numbers.discard(3)  # Does not raise an error if element not found
print("After removing an element:", unique_numbers)

After removing an element: {1, 2, 4, 5, 6}


In [ ]:
# Set operations
set_a = {1, 2, 3}
set_b = {3, 4, 5}
print("Set A:", set_a)
print("Set B:", set_b)

# Union
print("Union (A | B):", set_a | set_b)

# Intersection
print("Intersection (A & B):", set_a & set_b)

# Difference
print("Difference (A - B):", set_a - set_b)

Set A: {1, 2, 3}
Set B: {3, 4, 5}
Union (A | B): {1, 2, 3, 4, 5}
Intersection (A & B): {3}
Difference (A - B): {1, 2}


1.3 **Tuple**

In [ ]:
# Creating a tuple
coordinates = (10, 20, 30)
print("Original tuple:", coordinates)

# Accessing elements
print("First coordinate:", coordinates[0])

# Attempting to modify a tuple (this will cause an error if uncommented)
# coordinates[0] = 15  # Uncomment this line to see the immutability error

# Tuples can be used as keys in dictionaries because they are immutable
locations = {
    (10, 20): "Park",
    (30, 40): "Museum"
}
print("Using tuple as dictionary keys:", locations)

1.4 **List vs Set vs Tuple**

In [ ]:

# Creating a list, set, and tuple with the same elements
data_list = [1, 2, 2, 3, 4]
data_set = {1, 2, 2, 3, 4}
data_tuple = (1, 2, 2, 3, 4)

In [ ]:
# 1. Allowance of Duplicates
print("\n1. Allowance of Duplicates")
print("List:", data_list)   # Allows duplicates
print("Set:", data_set)     # Removes duplicates
print("Tuple:", data_tuple) # Allows duplicates

In [ ]:
# 2. Order of Elements
print("\n2. Order of Elements")
print("List (Ordered):", data_list)
print("Set (Unordered):", data_set)  # May print in a different order
print("Tuple (Ordered):", data_tuple)

In [ ]:
# 3. Mutability
print("\n3. Mutability")
# Lists are mutable
data_list[0] = 99
print("List after modification:", data_list)
# Sets are mutable (add or remove elements)
data_set.add(5)
print("Set after adding an element:", data_set)
# Tuples are immutable (uncommenting below will cause an error)
# data_tuple[0] = 99

In [ ]:
# Summary
print("\n\n=== Summary ===")
print("List: Ordered, Mutable, Allows Duplicates")
print("Set: Unordered, Mutable, No Duplicates")
print("Tuple: Ordered, Immutable, Allows Duplicates")

**Introduce "For" Loop in Python**

In [ ]:
list_1 = ["text0","text1","text2"]
print(list_1[0])
print(list_1[1])
print(list_1[2])

text0
text1
text2


In [ ]:
#method 1: scan every element in list then process one by one
list_1 = ["text0","text1","text2"]
for word in list_1: # word run from "text0" -> "text1" ->"text2"
  print(word )

In [ ]:
#method 2: find the range of the list, then scan in that range
list_1= ["text0","text1","text2"]
for i in range(len(list_1)): # i run from 0 -> 1 -> 2
  print(list_1[i])

text0
text1
text2


In [ ]:
len(list_1)

In [ ]:
range(len(list_1))

**2. Dictionary**

In [ ]:
dict_test ={'Me':4,'i':3,'we':5, 'myself':3,'our':2, 'ours':1, 'ourselves':4}
dict_test["we"]

5

In [ ]:
dict_test["our"] = 4 # write to dictionary
print(dict_test)

{'Me': 4, 'i': 3, 'we': 5, 'myself': 3, 'our': 4, 'ours': 1, 'ourselves': 4}


In [ ]:
# display all term which have value >=3
for term, value in dict_test.items():
  if value >=3:
    print(term, value)

Me 4
i 3
we 5
myself 3
our 4
ourselves 4


**Create a function in python**


In [ ]:
#calculate tf (term frequency) in a list
doc_list= ['this', 'is', 'another', 'example', 'another', 'example', 'example']

In [ ]:
# I want to calculate term frequency of term "this" in a doc_list
doc_list_length = len(doc_list)
doc_list_length

In [ ]:
#term frequency of term "this"
doc_list.count("this")/doc_list_length

0.14285714285714285

In [ ]:
# create tf function
def tf(term, list):
    tf = list.count(term)/len(list)
    return tf

In [ ]:
#calculate tf
print("tf of this:", tf("this",doc_list))
print ("tf of example:",tf("example",doc_list))

tf of this: 0.14285714285714285
tf of example: 0.42857142857142855


**3. Strings**

In [ ]:
#creae string
strings ="I went to the woods because I wished to live deliberately"
#show the string
strings

'I went to the woods because I wished to live deliberately'

**Work with strings**

In [ ]:
#show the string element
strings[0]

'I'

In [ ]:
#find a characters/words
print(strings.find("woods")) #return Index if found and -1 otherwise.

14


In [ ]:
sentence="I went to the woods because I wished to live deliberately, to front only the essential facts of life..."

In [ ]:
sentence.lower()

'i went to the woods because i wished to live deliberately, to front only the essential facts of life...'

In [ ]:
sentence.upper()

'I WENT TO THE WOODS BECAUSE I WISHED TO LIVE DELIBERATELY, TO FRONT ONLY THE ESSENTIAL FACTS OF LIFE...'

In [ ]:
sentence="I went to the woods because I wished to live deliberately, to front only the essential facts of life..."

In [ ]:
sentence.capitalize()

'I went to the woods because i wished to live deliberately, to front only the essential facts of life...'

In [ ]:
sentence[0]

'I'

In [ ]:
sentence[-1]

'.'

In [ ]:
sentence[1:10]

# B. Connect to google drive and loading data

1. Upload "gutenberb" data to your Colab Notebooks folder in google drive
2. connect your vitural machine to your google drive.

In [ ]:
#Mount google drive to google colab virtual machine
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
# Read from file "shakespeare-hamlet.txt and print its content
hamlet_text = open('/content/drive/My Drive/Colab Notebooks/data/hamlet.txt').read()
print(hamlet_text)

In [ ]:
#another way
mydrive ="/content/drive/My Drive/Colab Notebooks/"
hamlet_text = open(mydrive+'gutenberg/shakespeare-hamlet.txt').read()
print(hamlet_text)

# C. Numpy

In [ ]:
# Python Code: Introduction to NumPy

import numpy as np
# 1. Why Use NumPy?
# NumPy is faster and more efficient than Python lists for numerical computations.
print("1. Why Use NumPy?")
list_data = [1, 2, 3, 4]
numpy_array = np.array([1, 2, 3, 4])
print("Python list:", list_data)
print("NumPy array:", numpy_array)
print()

=== Introduction to NumPy ===

1. Why Use NumPy?
Python list: [1, 2, 3, 4]
NumPy array: [1 2 3 4]



In [ ]:

# 2. Creating NumPy Arrays
print("2. Creating NumPy Arrays")
# From a Python list
array_from_list = np.array([10, 20, 30])
print("Array from list:", array_from_list)

# Using built-in functions
zeros_array = np.zeros((2, 3))  # 2x3 array filled with zeros
ones_array = np.ones((3, 2))   # 3x2 array filled with ones
range_array = np.arange(0, 10, 2)  # Range from 0 to 10 with step 2
print("Zeros array:\n", zeros_array)
print("Ones array:\n", ones_array)
print("Range array:", range_array)

# Random numbers
random_array = np.random.rand(3, 3)  # 3x3 array with random values
print("Random array:\n", random_array)
print()




2. Creating NumPy Arrays
Array from list: [10 20 30]
Zeros array:
 [[0. 0. 0.]
 [0. 0. 0.]]
Ones array:
 [[1. 1.]
 [1. 1.]
 [1. 1.]]
Range array: [0 2 4 6 8]
Random array:
 [[0.14961428 0.13077073 0.78815235]
 [0.45215299 0.96897964 0.97041189]
 [0.29236437 0.33552308 0.56239744]]



In [ ]:
# 3. Array Operations
print("3. Array Operations")
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Element-wise operations
print("Addition:", a + b)
print("Multiplication:", a * b)
print("Exponentiation:", a ** 2)

# Broadcasting
print("Broadcasting (Add scalar):", a + 10)
print()



In [ ]:
# 4. Indexing and Slicing
print("4. Indexing and Slicing")
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Matrix:\n", matrix)

# Accessing elements
print("Element at (0, 0):", matrix[0, 0])

# Slicing
print("First row:", matrix[0, :])
print("First column:", matrix[:, 0])
print("Submatrix:\n", matrix[1:3, 1:3])
print()



4. Indexing and Slicing
Matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Element at (0, 0): 1
First row: [1 2 3]
First column: [1 4 7]
Submatrix:
 [[5 6]
 [8 9]]



In [ ]:
# 5. Shape and Reshaping
print("5. Shape and Reshaping")
array = np.arange(12)
print("Original array:", array)
reshaped_array = array.reshape(3, 4)
print("Reshaped to 3x4:\n", reshaped_array)
print()

#

In [ ]:
#6. Statistical Functions
print("6. Statistical Functions")
data = np.array([10, 20, 30, 40, 50])
print("Data:", data)
print("Mean:", np.mean(data))
print("Sum:", np.sum(data))
print("Standard deviation:", np.std(data))
print("Max:", np.max(data))
print("Min:", np.min(data))
print()

# 7. Useful Functions
print("7. Useful Functions")
array = np.array([1, 2, 3, 4, 5])
print("Original array:", array)
print("Cumulative sum:", np.cumsum(array))  # Cumulative sum
print("Sorted array:", np.sort(array))  # Sort elements
print()

# 8. Matrix Operations
print("8. Matrix Operations")
matrix_a = np.array([[1, 2], [3, 4]])
matrix_b = np.array([[5, 6], [7, 8]])

# Matrix multiplication
result = np.dot(matrix_a, matrix_b)
print("Matrix A:\n", matrix_a)
print("Matrix B:\n", matrix_b)
print("Matrix multiplication result:\n", result)
print()

# Summary
print("=== Summary ===")
print("NumPy is a powerful library for numerical computations, providing:")
print("- Faster operations compared to Python lists.")
print("- A wide variety of built-in functions for data manipulation.")
print("- Support for matrix and linear algebra operations.")
print()

6. Statistical Functions
Data: [10 20 30 40 50]
Mean: 30.0
Sum: 150
Standard deviation: 14.142135623730951
Max: 50
Min: 10

7. Useful Functions
Original array: [1 2 3 4 5]
Cumulative sum: [ 1  3  6 10 15]
Sorted array: [1 2 3 4 5]

8. Matrix Operations
Matrix A:
 [[1 2]
 [3 4]]
Matrix B:
 [[5 6]
 [7 8]]
Matrix multiplication result:
 [[19 22]
 [43 50]]

=== Summary ===
NumPy is a powerful library for numerical computations, providing:
- Faster operations compared to Python lists.
- A wide variety of built-in functions for data manipulation.
- Support for matrix and linear algebra operations.



# D. Pandas

In [ ]:
# Python Code: Introduction to Pandas

import pandas as pd

# 1. Why Use Pandas?
# Pandas is used for data manipulation and analysis. It provides data structures like Series and DataFrame.

# 2. Creating Data Structures: Series and- DataFrame
print("2. Creating Pandas Data Structures")

# Series: A one-dimensional array with labels
data_series = pd.Series([10, 20, 30, 40], index=["A", "B", "C", "D"])
print("Series:")
print(data_series)

# DataFrame: A two-dimensional table with labeled axes
data_frame = pd.DataFrame({
    "Name": ["Alice", "Bob", "Charlie"],
    "Age": [25, 30, 35],
    "Salary": [50000, 60000, 70000]
})
print("\nDataFrame:")
print(data_frame)

print("\n")



2. Creating Pandas Data Structures
Series:
A    10
B    20
C    30
D    40
dtype: int64

DataFrame:
      Name  Age  Salary
0    Alice   25   50000
1      Bob   30   60000
2  Charlie   35   70000




In [ ]:
# Create a simple DataFrame
data = {
    "Name": ["Alice", "Bob", "Charlie", "David", "Eve"],
    "Age": [25, 30, 35, 28, 40],
    "Salary": [50000, 60000, 70000, 55000, 80000],
    "Department": ["HR", "IT", "Finance", "Marketing", "HR"]
}

df = pd.DataFrame(data)

# Save to CSV
df.to_csv("example.csv", index=False)
print("example.csv created!")


In [ ]:
# 3. Reading and Writing Data
print("3. Reading and Writing Data")
# Writing to a CSV file
data_frame.to_csv("example.csv", index=False)
print("Data written to 'example.csv'.")

# Reading from a CSV file
read_data = pd.read_csv("example.csv")
print("Data read from 'example.csv':")
print(read_data)

print("\n")

# 4. Exploring Data
print("4. Exploring Data")
print("DataFrame:")
print(data_frame)

# Shape of the DataFrame
print("\nShape of the DataFrame:", data_frame.shape)

# Columns in the DataFrame
print("Columns:", data_frame.columns)

# Head and tail
print("\nFirst two rows (head):")
print(data_frame.head(2))
print("\nLast two rows (tail):")
print(data_frame.tail(2))

print("\n")





In [ ]:
# 5. Selecting and Filtering Data
print("5. Selecting and Filtering Data")
print("Original DataFrame:")
print(data_frame)

# Selecting a column
print("\nSelect 'Name' column:")
print(data_frame["Name"])

# Filtering rows
print("\nFilter rows where Age > 25:")
print(data_frame[data_frame["Age"] > 25])

print("\n")

# 6. Adding and Removing Data
print("6. Adding and Removing Data")

# Adding a new column
data_frame["Department"] = ["HR", "IT", "Finance"]
print("\nAfter adding a 'Department' column:")
print(data_frame)

# Removing a column
data_frame = data_frame.drop("Department", axis=1)
print("\nAfter removing the 'Department' column:")
print(data_frame)

# Adding a new row
new_row = {"Name": "David", "Age": 28, "Salary": 55000}
data_frame = data_frame.append(new_row, ignore_index=True)
print("\nAfter adding a new row:")
print(data_frame)

print("\n")



In [ ]:
# 7. Grouping and Aggregating
print("7. Grouping and Aggregating")

# Grouping by 'Age' and calculating the mean salary
grouped_data = data_frame.groupby("Age")["Salary"].mean()
print("Grouped data (Mean Salary by Age):")
print(grouped_data)

print("\n")

# 8. Handling Missing Data
print("8. Handling Missing Data")

# Creating a DataFrame with missing values
data_with_nan = pd.DataFrame({
    "Name": ["Alice", "Bob", "Charlie", "David"],
    "Age": [25, None, 35, 28],
    "Salary": [50000, 60000, None, 55000]
})
print("DataFrame with missing values:")
print(data_with_nan)

# Filling missing values
filled_data = data_with_nan.fillna({"Age": 30, "Salary": 0})
print("\nAfter filling missing values:")
print(filled_data)

# Dropping rows with missing values
dropped_data = data_with_nan.dropna()
print("\nAfter dropping rows with missing values:")
print(dropped_data)

print("\n")




In [ ]:
# 9. Summary Statistics
print("9. Summary Statistics")
print("DataFrame:")
print(data_frame)

# Summary statistics
print("\nSummary statistics:")
print(data_frame.describe())

# Individual statistics
print("\nMean Age:", data_frame["Age"].mean())
print("Total Salary:", data_frame["Salary"].sum())

print("\n")